### ISSUE TITLE
fix: DB 인스턴스 연결 오류

### ISSUE THREAD

**Issue by dusunax** [EnhancementPlayGround/nest_tdd#30]
## Error: Handshake inactivity timeout
- RDS를 새로 만들면서 DB 연결에 문제가 생김
<img width="400" alt="image" src="https://github.com/EnhancementPlayGround/nest_tdd/assets/94776135/8f27737c-b623-4a16-9a15-c538d709e6f3">

## 내용
- 원인:
  - 챕터3 진행 중, AWS 리전을 전체적으로 정리 (ap-northeast-2로 통일하고 미사용 서비스는 종료 등)하고 있습니다
  - 현재 ap-northeast-2 리전에 새로 만든 DB를 연결 시, 다음 에러 메시지와 함께 timeout이 발생합니다.
- 확인할 것:
  - env의 사용자, 비밀번호, 호스트 
  - RDS Configuration 확인
- 중요도: 
  - timeout으로 서버가 종료되기 때문에 바로 확인 필요

<img width="466" alt="image" src="https://github.com/EnhancementPlayGround/nest_tdd/assets/94776135/fc9b7be1-0616-4921-b1c2-a662d551e8e6">

```tsx
[Nest] 83071  - 01/06/2024, 11:29:56 AM   ERROR [ExceptionHandler] Handshake inactivity timeout
Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/Users/du/repository/pipeline-hp1/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at Handshake.emit (node:events:514:28)
    at Handshake._onTimeout (/Users/du/repository/pipeline-hp1/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:124:8)
```
### DB Instance 삭제 및 재생성
- 체크: public access(예), username, password(메모), endpoint(오탈자 확인), 인증은 password로 진행
- Create parameter group => 인코딩 / utf8 관련 설정
- Security Groups의 Inbound rules에서 IPv4랑 IPv6 허용

### env 업데이트
- 감춰진 admin 비밀번호의 오류 등을 방지하기 위해, 인스턴스를 새로 생성하였으므로 이를 적용하여 업데이트 
  (휴먼 에러 확인 및 로컬에 백업)

### Todo: VSC Database 재연결하기
<img width="800" alt="image" src="https://github.com/EnhancementPlayGround/nest_tdd/assets/94776135/0086e4e4-4c67-4102-abd2-01c8fe13482d">

- 로그인 시 기존 timeout이 발생하다가 configuration 수정 이후 no database exist로 메시지 변경된 것으로 보아, parameter group이나 security group / inbound roules에 문제가 있었던 것으로 보입니다.
- 이후 같은 현상 발생 시 -> (1)parameter group (2)security group / inbound roules 체크

<img width="392" alt="image" src="https://github.com/EnhancementPlayGround/nest_tdd/assets/94776135/721841a7-3bc1-4441-a7f9-dfa3a82a68c1">

### 중간 결론 
- 이후 DB timeout 관련 오류 발생 시
  - (1)Workbench나 VSC에서 계정의 로그인이 정상적으로 되는 지 확인
  - (2)parameter group 설정 체크
  - (3)security group / inbound roules 설정 체크
- 레퍼런스
  - https://debut12.tistory.com/34

## `Error: Handshake inactivity timeout`는 오류 해결되지 않음
- 추가 확인
- database의 Inbound rule 
<img width="408" alt="image" src="https://github.com/EnhancementPlayGround/nest_tdd/assets/94776135/8b3c35f4-78d9-4e0c-a145-ebed5d0227ef">

**Comment by dusunax** [comment]
### 아래 내용 반영 후 오류 수정됨 => https://github.com/EnhancementPlayGround/nest_tdd/issues/29#issuecomment-1879971193
